TEMPLATE = app
QT = gui core sql network xml
CONFIG += qt warn_on release
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
SOURCES = src/main.cpp src/gmail.cpp src/qtgmail.cpp src/gmailWidget.cpp 
HEADERS += src/gmail.h src/qtgmail.h src/gmailWidget.h 
FORMS += ui/gmail.ui
