TEMPLATE = app
QT = gui core network xml phonon
CONFIG += qt warn_on release #qxt
#QXT += core gui
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
SOURCES = src/main.cpp src/gmail.cpp src/qtgmail.cpp src/gmailWidget.cpp src/login.cpp src/log.cpp 
HEADERS += src/gmail.h src/qtgmail.h src/gmailWidget.h src/login.h src/log.h  
FORMS += ui/gmail.ui ui/login.ui
RESOURCES += gmail.qrc 
